int _putchar (char c);
void print_alphabet(void);
void print_alphabet_x10(void);
void isalpha(int c);
void print_sign(int n);
int _abs(int);
int print_last_digit(int);
int jack_bauer(int);
int times_table(void);
int add(int a, int b);
int print_to_98(int n);
void print_tomes_table(int n);
